### PR TITLE
Towards radiospectra

### PR DESCRIPTION
**Pull request by dpshelio**
This is few changes towards #18

- [ ] to rename package
- [x] to update sunpy deprecation link

### CODE REVIEW

**Comment by Cadair** [comment]
How many random commit status bots does one repo need?!!

**Comment by nabobalis** [comment]
WHY DONT WE HAVE ALL THESE?

**Comment by dpshelio** [comment]
@Cadair - they are FREE!! (though we may be helping the global warming with it)...

**Comment by Cadair** [comment]
They are also all noise and never going to pass

**Comment by dpshelio** [comment]
But I enjoying that noise and learn about other stuff :stuck_out_tongue_closed_eyes:

**Pull request merged**
